# MySQL Settings  
# Use root/password as MySQLcredentials
# Use app/password as MySQLcredentials

version: '3.3'
services:
  app:
    container_name: laravelApp-docker
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    image: mokchend:laravel-app-docker
    ports:
      - 8080:80
      - 4443:443
    volumes:
      - .:/app
    links:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel_docker
      DB_USERNAME: app
      DB_PASSWORD: password
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    container_name: laravelApp-mysql-docker
    command: --disable-partition-engine-check
    restart: always
    image: mysql:8.0.13
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: laravel_docker
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    #Your mysql data will be saved on you local filesystem.
    volumes:
      - /Users/chendamok/docker_volumes/mysql_data:/var/lib/mysql
  redis:
    container_name: laravelApp-redis-docker
    image: redis:5.0-alpine
    ports:
      - 16379:6379     